#+TITLE:  数学小结
#+EMAIL:  huangxiaoweigx AT gmail DOT com
#+AUTHOR: 黄效威
#+DATE:   2015-09-09
#+OPTIONS: toc:nil,LaTex=t
# +LATEX_CLASS: article
# Latex options: twoside,twocolumn,titlepage                                                                                                   
#+LaTeX_CLASS_OPTIONS: [a4paper,titlepage]
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Adobe Heiti Std,ItalicFont=Adobe Kaiti Std]{Adobe Song Std L}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{arrows,graphs,intersections,arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri,calc,through,trees,mindmap}
#+LATEX_HEADER: \usetikzlibrary{patterns}
#+LATEX: \newcommand{\fstwenty}{\fontsize{20pt}{\baselineskip}\selectfont}
#+LATEX: \newcommand{\fsthirty}{\fontsize{30pt}{\baselineskip}\selectfont}
#+LATEX: \setCJKfamilyfont{fsong}{Adobe Fangsong Std R}
#+LATEX: \setCJKfamilyfont{hei}{Adobe Heiti Std R}
#+LATEX: \setCJKfamilyfont{song}{Adobe Song Std L}
#+LATEX: \setCJKfamilyfont{kai}{Adobe Kaiti Std R}
#+LATEX: \newcommand{\fsong}{\CJKfamily{fsong}}
#+LATEX: \newcommand{\hei}{\CJKfamily{hei}}
#+LATEX: \newcommand{\song}{\CJKfamily{song}}
#+LATEX: \newcommand{\kai}{\CJKfamily{kai}}

* Introduction
  #+BEGIN_COMMENT
  #+BEGIN_LATEX
  \begin{tikzpicture}
  \draw[even odd rule,pattern = bricks] (0,0) circle [radius = 2cm] (0,0) circle [radius=1cm];
  \draw[double] (3,0) -- (4,0);
  \end{tikzpicture}
  \tikz \graph [grow down, branch right] {
  root -> {left, right -> {child, child} }
  };
  #+END_LATEX
  #+END_COMMENT
* The Probability Theory(概率论)
** 概率论的基本概念
   - 随机现象 :: 在个别试验中其结果呈现出不确定性, 在大量重复试验中其
     结果又具有统计规律性的现象,称之为随机现象.
   - 随机试验 :: 具有以下三个特点的试验称为随机试验:
     1. 可以在相同的条件下重复地进行;
     2. 每次试验的结果可能不止一个,并切能事先确定试验的所有可能结果;
     3. 进行一次试验之前不能确定哪一个结果会出现.
   - 样本空间 :: 随机试验 $E$ 的所有可能的结果组成的集合称为 $E$ 的
     样本空间, 记为 $S$. 样本空间的元素, 即 $E$ 的每个结果,称为
     *样本点*.
   - 随机事件 :: 随即试验 $E$ 的样本空间 $S$ 的子集称为 $E$ 的随机
     事件,简称为 *事件*.在每次试验中,当且仅当这一子集的一个样本点出
     出现时,称这一 *事件发生*.
   - 基本事件 :: 由一个样本点组成的单点集,称为基本事件.
   - 事件间的关系及运算 :: 事件是一个集合,因而事件间的关系及运算自然
     可以按照集合论中集合之间的关系及运算来处理.设试验 $E$ 的样本空
     间为 $S$, $A,B,A_k(k=1,2,\cdots)$ 是 $S$ 的子集, 则
     1. 若 $A\subset B$ ,则称事件 $B$ 包含事件 $A$ ,这指的是事件
	$A$ 发生必导致事件 $B$ 发生; \\
	若 $A\subset B$ 且 $B\subset A$, 即 $A=B$, 称事件 $A$ 与
	事件 $B$ *相等*.
     2. 事件 $A\cup B = \{x \in A \vee x \in B\}$ 称为事件 $A$ 和事件
	$B$ 的 *和事件*,当且仅当 $A,B$ 中至少有一个事件发生时, 
	事件 $A\cup B$ 发生.
     3. 事件 $A\cap B = \{x \in A \wedge x \in B\}$ 称为事件 $A$ 和
	事件 $B$ 的 *积事件*,当且仅当 事件 $A,B$ 同时件发生时, 事件
	$A\cap B$ 发生, $A\cap B$ 可以简写为 $AB$.
     4. 事件 $A - B = \{x \in A \wedge x \notin B\}$ 称为事件 $A$ 
        和事件 $B$ 的 *差事件*,当且仅当 事件 $A$ 发生, 事件 $B$ 
	不发生时, 事件 $A - B$ 发生.
     5. 事件 $A\cap B = \Phi$ 则称事件 $A$ 和 事件 $B$ 是 
        *互不相容* 的 或 *互斥* 的, 这指的是事件 $A$ 和事件 $B$ 不能
	同时发生, 基本事件事是互不相容事件.
     6. 事件 $A \cup B = S$ 且 $A\cap B = \Phi$ 则称事件 $A$ 
	和 事件 $B$ 是互为 *逆事件*, 或称为 *对立事件*.这指的是每次试
	验时,事件 $A, B$ 中 必有一个发生且仅有一个发生. $A$ 的逆事件
	记为 $\overline{A}$, $\overline{A} = S - A$.
   - 概率 :: 设 $E$ 是随机试验, $S$ 是它的样本空间, 对于 $E$ 的每一事
     件 $A$, 赋予一个实数, 记为 $P(A)$, 称为事件 $A$ 的概率.概率满足
     下列条件:
     1. *非负性*: 对于每个事件 $A$, 有 $P(A) \ge 0$;
     2. *规范性*: 对必然事件 $S$, 有 $P(S) = 1$;
     3. *可列加性*: 设 $A_1,A_2,\cdots$ 是两两互不相容的事件,即对于
	$A_{i} A_{j} = \Phi, i \neq j, i,j=1,2,\cdots$, 有
	$$ P(A_1 \cup A_2 \cup \cdots) = P(A_1) + P(A_2) + \cdots $$
   - 等可能概型 :: 具有以下两个特点的试验,称为等可能概型,也称为
		   *古典概型*.
     1. 试验的样本空间只包含有限个元素;
     2. 试验中每个基本事件发生的可能性相同.
   - 条件概率 :: 设 $A,B$ 是两个事件,且 $P(A)>0$, 称
		 $$ P(B|A) = \frac{P(AB)}{P(A)}  $$
     为在事件 $A$ 发生的条件下事件 $B$ 发生的 *条件概率* ,不难验证
     条件概率 $P( \bullet | A)$ 符合概率定义中的三个条件.
     1. *非负性*: 对于每个事件 $S$, 有 $P(B|A) \ge 0$;
     2. *规范性*: 对必然事件 $S$, 有 $P(S|A) = 1$;
     3. *可列加性*: 设 $B_1,B_2,\cdots$ 是两两互不相容的事件,则有
	$$ P(\cup_{i=1}^{\infty}B_{i}|A) = \sum_{i=1}^{\infty}P(B_{i}|A)$$
   - 乘法定理 :: 由条件概率的定义可知,当 $P(A) \neq 0$ 时, 有
		 $$P(AB) = P(B|A)P(A)$$
     称上式为 *乘法公式* .同理,可推广到多个.若 $P(AB) \neq 0$, 则有
		 $$ P(ABC) = P(C|AB)P(B|A)P(A) $$
   - 划分 :: 设 $S$ 是试验 $E$ 的样本空间, $B_1,B_2,\cdots,B_n$ 是
     $E$ 的一组事件,若满足下列两个条件:
     1. $B_{i}B_{j} = \Phi, i\neq j, i,j=1,2,\cdots,n$;
     2. $B_1 \cup B_2 \cup \cdots \cup B_n = S$;
     则称 $B_1,B_2,\cdots,B_n$ 是样本空间 $S$ 的一个划分.\\
     若 $B_1,B_2,\cdots,B_n$ 是样本空间 $S$ 的一个划分,则每次试验,
     $B_1,B_2,\cdots,B_n$ 必有一个发生且仅有一个发生.
   - 全概率公式 :: 设 $S$ 是试验 $E$ 的样本空间, $B_1,B_2,\cdots,B_n$
     是试验 $E$ 的样本空间 $S$ 的一个划分且 $P(B_i) > 0$, $A$ 为
     $E$ 的事件,则
        | $P(A)$ | = | $P(AS)$                               |
        |        | = | $P(A\sum_{i=1}^{n}B_i)$               |
        |        | = | $\sum_{i=1}^{n}P(AB_i)$               |
        |        | = | $\sum_{i=1}^{n}P(A\vert B_{i})P(B_i)$ |
   - 贝叶斯公式 :: 设 $S$ 是试验 $E$ 的样本空间, $A$ 为试验 $E$ 的
     事件, $B_1,B_2,\cdots,B_n$ 是试验 $E$ 的样本空间 $S$ 的一个划分
     且 $P(A) > 0$, $P(B_i) > 0 (i=1,2,\cdots)$, 则 
     $$P(B_{i}|A) = \frac {P(B_{i})P(A|B_{i})} {\sum_{j=1}^{n}P(A|B_{j})P(B_{j})} (i=1,2,\cdots,n) $$
   - 相互独立 :: 设 $A,B$ 是两事件, 若满足等式
     $$ P(AB) = P(A)P(B), $$ 则称事件 $A$ 和事件 $B$ 是相互独立的,
     简称 *独立*.两个推论:
     1. 若事件 $A_1,A_2,\cdots,A_n (n \ge 2)$ 相互独立, 则其中任意
        $k (2 \le k \le n)$ 个事件也相互独立;
     2. 若事件 $A_1,A_2,\cdots,A_n (n \ge 2)$ 相互独立, 则将 
	$A_1,A_2,\cdots,A_n$ 中任意个事件换成它们的对立事件,所得
	得 $n$ 个事件仍然是相互独立.

     

** 随机变量及其分布
*** 概念
    - 随机变量 :: 设随机试验的样本空间为 
      $S=\{e\}$ [fn:1], $X=X(e)$
      是定义在样本空间 $S$ 上的实值单值函数,称 $X=X(e)$ 为随机变量.
    - 离散型随机变量 :: 有些随机变量,它全部可能取到的值是有限个或可列无限多个,这种
      随机变量称为离散型随机变量.设离散型随机变量 $X$ 所有可能取的值为 
      $x_k(k=1,2,\cdots)$, $X$ 取各个可能值的概率,即事件($X=x_{k}$)的概率,为
        | $P(X=x_{k}) = p_{k}, k=1,2,\cdots$   | (2.1) |
      由概率的定义, $p_k$ 满足如下两个条件:
      1) $p_k \ge 0, k=1,2,\cdots$ ;
      2) $\sum_{i=1}^{\infty} p_{k} = 1$.
      同时,称(2.1)式为离散型随机变量 $X$ 的 *分布律*. 分布律也可以写成如下的表格
      形式.
      | $X$   | \vert | $x_1$ | $x_2$ | \cdots | $x_k$ | \cdots |
      |-------+-------+-------+-------+--------+-------+--------|
      | $P_k$ | \vert | $P_1$ | $P_2$ | \cdots | $P_k$ | \cdots |
      |       |       |       |       |        |       |        | 
  
    - 伯努利试验 :: 设试验 $E$ 只有两个可能结果: $A$ 及 $\overline{A}$,则称 $E$ 为
      伯努利试验.设 $P(A)=p(0<p<1)$, 此时 $P(\overline{A}) =1-p$, 将 $E$ 独立重复
      地进行 $n$ 次,则称这一串重复独立试验为 $n$ *重伯努利试验*.
    - 分布函数 :: 设 $X$ 是一个随机变量, $x$ 是任意实数,函数
      $$\mathsf{F}(x) = P\{X\le x\}, -\infty < x < \infty$$
      称为 $X$ 的分布函数.\\
      对于任意实数 $x_1,x_2(x_1 < x_2)$,有
      | $P\{x_{1}<X\le x_{2}\}$  | = | $P\{X\le x_2\} - P\{X\le x_1\}$     |
      |                          | = | $\mathsf{F}(x_2) - \mathsf{F}(x_1)$ |
      |                          |   |                                     |
      分布函数 $\mathsf{F}(x)$ 具有以下的基本性质:
      1. $\mathsf{F}(x)$ 是一个不减函数.对于任意实数 $x_1,x_2(x_1 < x_2)$,有
	 $$\mathsf{F}(x_2) - \mathsf{F}(x_1) = P\{x_{1}<X\le x_2\} \ge 0$$

      2. $0 \le \mathsf{F}(x) \le 1$,且
         $$ \mathsf{F}(-\infty)=\lim{}_{x\rightarrow -\infty}\mathsf{F}(x) = 0$$
         $$ \mathsf{F}(\infty)=\lim{}_{x\rightarrow \infty}\mathsf{F}(x) = 1$$
	 $$ \mathsf{F}(x+0) = \mathsf{F}(x) $$
    - 连续型随机变量 :: 如果对于随机变量 $X$ 的分布函数 $\mathsf{F}(x)$ ,存在非负
      函数 $f(x)$, 使得对于任意实数 $x$ 有
      $$ \mathsf{F}(x) = \int_{-\infty}^{x}f(x)dx,$$
      则称 $X$ 为连续型随机变量,其中函数 $f(x)$ 称为 $X$ 的概率密度函数.简称
      *概率密度*.\\
      由定义可知,概率密度 $f(x)$ 具有以下性质:
      1. $f(x) \ge 0$;

      2. $\int_{-\infty}^{\infty}f(x)dx=1$;

      3. 对于任意实数 $x_1 , x_2 (x_1 \le x_2)$,
	 $$P\{ x_1 \le X \le x_2 \} = \mathsf{F}(x_2 ) - \mathsf{F}(x_1 ) = \int_{x_1}^{x_2}f(x)dx $$

      4. 若 $f(x)$ 在点 $x$ 处连续,则有 $\mathsf{F}^{'}(x) = f(x)$.


*** 概率模型
    - (0 --- 1) 分布 :: 设随机变量 $X$ 只可能取0与1两个值,它的分布律是
      $$ P(X=k)=p^{k}(1-p)^{1-k}, k=0,1\ \ (0 < p <1)$$
      则称 $X$ 服从以 $p$ 为参数的 (0 --- 1) 分布或两点分布.
    - 二项分布 :: 以 $X$ 表示 $n$ 重伯努利试验中事件 $A$ 发生的次数, 则 $X$ 是一个
      随机变量,其可能值为 $0,1,2,\cdots,n$.由于各次试验相互独立,因此事件 $A$ 在指
      定的 $k(0\le k \le n)$ 次试验中发生, 在其他 $n-k$ 次试验中 $A$ 不发生(例如
      在前 $k$ 次试验中 $A$ 发生,而后 $n-k$ 次试验中 $A$ 不发生)的概率为
      \[ 
         \underbrace{p\bullet p \bullet \cdots \bullet p}_{k} \bullet
         \underbrace{(1-p) \bullet (1-p) \bullet \cdots \bullet (1-p)}_{n-k} = 
         p^{k}(1-p)^{n-k}
      \]
      这种指定的方式共有 $\mathsf{C}_{n}^{k}$ 种,它们是两两互不相容的,故在 $n$ 次
      试验中 $A$ 发生 $k$ 次的概率为 $\mathsf{C}_{n}^{k}p^{k}(1-p)^{n-k}$, 记
      $q=1-p$, 即有
      \[
        P(X=k)=\mathsf{C}_{n}^{k}p^{k}q^{n-k},k=0,1,2,\cdots,n
      \]
      显然
      $$ P(X=k)= \ge 0, k=0,1,2,\cdots,n $$
      \[
        \sum_{k=0}^{n}P(X=k) = \sum_{k=0}^{n}\mathsf{C}_{n}^{k}p^{k}q^{n-k}
        = (p+q)^{n} = 1.
      \]
      注意到 $\mathsf{C}p^{k}q^{n-k}$ 正好是二项式 $(p+q)^{n}$ 的展开式中出现 
      $p^{k}$ 的那一项.我们称随机变量 $X$ 服从参数为 $n,p$ 的 *二项分布*,并记
      为  $X \sim b(n,p)$.
      特别,当 $n=1$ 时二项分布化为
      $$ P(X=k)=p^{k}q^{1-k}, k=0,1.$$
      这就是 (0---1) 分布.
    - 泊松分布 :: 设随机变量 $X$ 所有可能取的值为 $0,1,2,\cdots$,而取各个值的概率为
      $$P(X=k)=\frac{\lambda^{k}\mathsf{e}^{-\lambda}}{k!},k=0,1,2,\cdots$$
      其中 $\lambda > 0$ 是常数,则称 $X$ 服从参数为 $\lambda$ 的 *泊松分布*, 记为
      $X \sim \pi (\lambda)$.
      易知, $P(X=k) \ge 0, k=0,1,2,\cdots$, 且有
      | $\sum_{k=0}^{\infty}P(X=k)$ | = | $\sum_{k=0}^{\infty} \frac{\lambda^{k}\mathsf{e}^{-\lambda}}{k!}$ |
      |                             | = | $\mathsf{e}^{-\lambda}\sum_{k=0}^{\infty}\frac{\lambda^k}{k!}$    |
      |                             | = | $\mathsf{e}^{-\lambda}$ [fn:2]                             |
      |                             | = | 1                                                                 |
    - 均匀分布 :: 若连续随机变量 $X$ 具有概率密度
      $$ f(x) = \left\{ \begin{array}{lr} \frac{1}{b-a},& a<x<b \\ 0, & others \end{array} $$
      则称 $X$ 在区间 $(a,b)$ 上服从 *均匀分布*, 记为 $X \sim U(a,b)$. $X$ 
      的分布函数为
      $$ F(x) = \left\{ \begin{array}{lr} 0, & x<a \\ \frac{x-a}{b-a},& a\le x<b \\ `1, & x\ge b \end{array} $$
    - 指数分布 :: 若连续随机变量 $X$ 具有概率密度
     $$ f(x) = \left\{ \begin{array}{lr} \frac{1}{\theta}e^{\frac{-x}{\theta}},& x>0 \\ 0, & others \end{array} $$
     其中 $\theta > 0$ 为常数,则称 $X$ 服从参数为 $\theta$ 的 *指数分布*, 其分布函数为
     $$ F(x) = \left\{ \begin{array}{lr} 1-e^{\frac{-x}{\theta}}, & x>0 \\ 0,& others \end{array} $$
     服从指数分布的随机变量 $X$ 具有 *无记忆性*,即对任意 $s,t>0$ ,有
     $$P\{X>s+t\vert X>s\} = P\{X>t\} $$
     事实上
     | $P\{X>s+t\vert X>s\}$ | = | $\frac{P\{(X>s+t)\bigcap (X>s)\}}{P\{X>s\}}$              |
     |                       | = | $\frac{P\{X>s+t\}}{P\{X>s\}}$                             |
     |                       | = | $\frac{1-F(s+t)}{1-F(s)}$                                 |
     |                       | = | $\frac{e^{\frac{-(s+t)}{\theta}}}{\mathsf{e}^{\frac{-s}{\theta}}}$        |
     |                       | = | $e^{\frac{-t}{\theta}}$                                   |
     |                       | = | $P\{X>t\}$                                                |
    - 正太分布 :: 若连续型随机变量 $X$ 的概率密度为
      $$f(x)=\frac{1}{\sqrt{2\pi}\sigma}e^{-\frac{(x-\mu)^2}{2\sigma{}^2}}.-\infty <x< \infty$$
      其中 $\mu,\sigma (\sigma >0)$ 为常数,则称 $X$ 服从参数为 $\mu,\sigma$ 的 
      *正太分布* 或 *高斯分布*, 记为 $X \sim N(\mu,\sigma{}^{2})$ .

* Footnotes

[fn:1] 用 $e$ 代表样本空间的元素,而样本空间记成 $\{e\}$.

[fn:2] 在数学分析中知道 $\mathsf{e}^{x} = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdots + \frac{x^k}{k!} + \cdots$
